### ISSUE TITLE
Spraygun should check for yarn before attempting to create a project

### ISSUE THREAD

**Issue by spilth** [carbonfive/spraygun#3]
I missed the Yarn requirement in the instructions ended up with a half-initialized project template:

```
→ npx spraygun -t react foobar
npx: installed 26 in 2.71s
exec git clone 'https://github.com/carbonfive/spraygun-react.git' /var/folders/3y/yg5886r95jj4t9tzd0nr2q6c0000gn/T/spraygun-1538579929679
Cloning into '/var/folders/3y/yg5886r95jj4t9tzd0nr2q6c0000gn/T/spraygun-1538579929679'...

  Generating your spraygun project...

  Project   /Users/bkelly/workspace/learning/react/foobar
  Template  react

Copying files from /Users/bkelly/.cache/spraygun/bc1fd58dfb46...
Running setup task from /Users/bkelly/workspace/learning/react/foobar/.spraygun.js...
exec: /bin/sh: yarn: command not found
```

It would be nice if spraygun checked for a yarn installation before attempting to initialize a project and exited early if it's not installed.

**Comment by mattbrictson** [comment]
Agreed, this is not great developer experience. The challenge fixing this is that spraygun itself does not have a dependency on yarn; rather it is the particular template (spraygun-react in this case) that requires it. Hence spraygun can't know until it has already cloned the template.

I suppose spraygun could clone to a temporary location first, then somehow interrogate the template for its dependencies, and abort if the dependencies are not met? Or perhaps simpler would be for spraygun to do some cleanup and provide a better error message if a template fails is to execute.

Any other suggestions?

**Comment by spilth** [comment]
How about having a convention for where a template's dependencies are located and then you can just `curl` the raw file from GitHub? (instead of cloning to a temporary location)

Cleaning up when the script files would be helpful too. I installed yarn and ran the command again, but of course the directly already existed and the script exited with an error.

**Comment by dylnclrk** [comment]
I like either:
* formally accepting `yarn` as a dependency for all spraygun projects
* creating a new convention for templates: a `.preflight.js` script that's run before cloning the template (in this case it would check for yarn)

**Comment by dylnclrk** [comment]
oh man this is an _old_ issue lol. Just realized it's from 2018 haha
